spring:
  application:
    name: jetcache-plus-example-school
  cloud:
    nacos:
      discovery:
        namespace: public
        server-addr: http://10.0.11.20:8848

dubbo:
  cloud:
    subscribed-services: jetcache-plus-example-school
  protocol:
    id: dubbo
    name: dubbo
    port: -1
  scan:
    base-packages: io.github.qy8502.jetcacheplusexample

jetcache:
  statIntervalMinutes: 5
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyPrefix: "cache:jetcache-plus-example:"
      keyConvertor: fastjson
      valueEncoder: jackson
      valueDecoder: jackson
      uri:
        - "redis://${redis.password}@10.0.11.20:6379"
        - "redis://${redis.password}@10.0.11.20:6380"
        - "redis://${redis.password}@10.0.11.20:6381"
        - "redis://${redis.password}@10.0.11.20:6382"
        - "redis://${redis.password}@10.0.11.20:6383"
        - "redis://${redis.password}@10.0.11.20:6384"

logging:
  level:
    root: WARN
    io.github.qy8502.jetcacheplus: DEBUG
    io.github.qy8502.jetcacheplusexample: DEBUG

server:
  port: 8081